networks:
  app_network:
    driver: bridge

volumes:
  mysqldata:
    driver: local

services:
  app:
    image: "php:8.3-apache"
    restart: "always"
    ports: 
      - "80:80" # 443 => https 
    volumes:
      - .:/var/www/html
    networks:
      - app_network
  database:
    image: "mysql:8"
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_db
    networks:
      - app_network
